import { Inter } from 'next/font/google'
import './globals.css'
import MouseGradient from '@/components/MouseGradient'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en" className={inter.className}>
      <body className="relative my-[100px] mx-[350px] overflow-hidden">
      <MouseGradient />
      {children}
      </body>
      </html>
  )
}
